# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty # so that graphql can install.  need C++11
sudo: false
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - dev
    - travis

r_github_packages:
  - jimhester/lintr # test with lints
  - jimhester/covr # after success

after_success:
  - LINTR=SKIP Rscript -e 'print(Sys.getenv("LINTR")); covr::codecov()'

env:
  - LINTR_COMMENT_BOT=false
